


const SET_ANSWERS = 'SET_ANSWERS';
const ANSWER_QUESTION_REQUEST = 'ANSWER_QUESTION_REQUEST';
const ANSWER_QUESTION_SUCCESS = 'ANSWER_QUESTION_SUCCESS';
const ANSWER_QUESTION_FAIL = 'ANSWER_QUESTION_FAIL';
export default  {
    ANSWER_QUESTION_REQUEST,
    ANSWER_QUESTION_SUCCESS,
    ANSWER_QUESTION_FAIL,
    SET_ANSWERS,
}