
const SET_REPLIES = 'SET_REPLIES';
const REPLY_ANSWER_REQUEST = 'REPLY_ANSWER_REQUEST';
const REPLY_ANSWER_SUCCESS = 'REPLY_ANSWER_SUCCESS';
const REPLY_ANSWER_FAIL = 'REPLY_ANSWER_FAIL';

export default  {
    SET_REPLIES,
    REPLY_ANSWER_REQUEST,
    REPLY_ANSWER_SUCCESS,
    REPLY_ANSWER_FAIL
}