export const SET_CAROUSEL_SIZE = 'SET_CAROUSEL_SIZE';
export const SET_CURRENT = 'SET_CURRENT';

export const ADD_TO_CART = 'ADD_TO_CART';
export const TOGGLE_CART_VISIBILITY = 'TOGGLE_CART_VISIBILITY';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const SET_ITEM_AMOUNT = 'SET_ITEM_AMOUNT';
export const SAVE_PURCHASES = 'SAVE_PURCHASES';
export const CLEAR_PURCHASES = 'CLEAR_PURCHASES';
export const FETCH_CART_REQUEST = 'FETCH_CART_REQUEST';
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS';
export const FETCH_CART_FAILURE = 'FETCH_CART_FAILURE';
export const HIDE_CART = 'HIDE_CART';

export const CHOOSE_DISH = 'CHOOSE_DISH';
export const SET_DISH_AMOUNT = 'SET_DISH_AMOUNT';
export const SET_DISHES = 'SET_DISHES';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_VISIBLE_AMOUNT = 'SET_VISIBLE_AMOUNT';
export const FETCH_DISH_REQUEST = 'FETCH_DISH_REQUEST';
export const FETCH_DISH_SUCCESS = 'FETCH_DISH_SUCCESS';
export const FETCH_DISH_FAILURE = 'FETCH_DISH_FAILURE';

export const TOGGLE_VISIBILITY = 'TOGGLE_USER_VISIBILITY';
export const HIDE_USER = 'HIDE_USER';
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_USER_EMAIL = 'SET_USER_EMAIL';
export const SET_ORDER_HISTORY = 'SET_ORDER_HISTORY';
export const LOGOUT = 'LOGOUT';
export const FETCH_LOGIN_REQUEST = 'FETCH_LOGIN_REQUEST';
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS';
export const FETCH_LOGIN_FAILURE = 'FETCH_LOGIN_FAILURE';
